version: '3.1'
services:
  itoken-admin:
    restart: always
    image: 10.0.2.27:5000/itoken-admin
    container_name: itoken-admin
    ports:
      - 8084:8084
    networks:
      - admin_network

networks:
  admin_network:
